blueprint:
  name: Paralelo Virtual
  description: Efetua o agrupamento de switches e lâmpadas para acionamento simultaneo.
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os devices para agrupar
      description: Você deve escolher entre os switches e lâmpadas instalados.
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input entrada_switchs
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0

mode: single